# Makefile
TARGET	= user_test
CC	= gcc
NVCC	= nvcc -arch sm_20 -cubin
LIBS	= -lcuda
CFLAGS	= -I /usr/local/cuda/include

all:
	gcc -o $(TARGET) $(CFLAGS) $(LIBS) main.c memcpy_async.c

clean:
	rm -f $(TARGET) *.cubin ./*~
