# Makefile
TREE_TARGET	= mmult_tree
RECT_TARGET	= mmult_rect
CC	= gcc
NVCC	= nvcc -arch sm_20 -cubin
LIBS	= -lcuda
CFLAGS	= -I /usr/local/cuda/include -g

all:
	$(NVCC) -o mmult_gpu.cubin mmult_gpu.cu
	gcc -o $(RECT_TARGET) $(CFLAGS) $(LIBS) mmult_rect.c mmult.c
	gcc -o $(TREE_TARGET) $(CFLAGS) $(LIBS) mmult_tree.c mmult.c

clean:
	rm -f $(TREE_TARGET) $(RECT_TARGET) *.cubin ./*~
