# Makefile
TARGET	= user_test
ARCH	= sm_20
CC	= gcc
CLANG	= clang -cc1 -nostdsysteminc -triple nvptx-unknown-unknown -fcuda-is-device -emit-llvm
LLC     = llc -march=nvptx64 -mcpu=$(ARCH)
PTXAS   = ptxas -arch $(ARCH)
LIBS	= -lucuda -lgdev
CFLAGS	= -L /usr/local/gdev/lib64 -I /usr/local/gdev/include

all:
	$(CLANG) -I . -o fmmul_gpu.ll clang/fmmul_gpu.cu
	$(LLC) -o fmmul_gpu.ptx fmmul_gpu.ll
	$(PTXAS) -o fmmul_gpu.cubin fmmul_gpu.ptx
	$(CC) -o $(TARGET) $(CFLAGS) main.c fmmul.c $(LIBS)

clean:
	rm -f $(TARGET) *.cubin *.ptx *.ll ./*~
