#ifndef NVRM_DEF_H
#define NVRM_DEF_H

#define NVRM_CHECK_VERSION_STR_CMD_STRICT		0
#define NVRM_CHECK_VERSION_STR_CMD_RELAXED		'1'
#define NVRM_CHECK_VERSION_STR_CMD_OVERRIDE		'2'
#define NVRM_CHECK_VERSION_STR_REPLY_UNRECOGNIZED	0
#define NVRM_CHECK_VERSION_STR_REPLY_RECOGNIZED		1

#define NVRM_FIFO_ENG_GRAPH	1
#define NVRM_FIFO_ENG_COPY0	2
#define NVRM_FIFO_ENG_COPY1	3
#define NVRM_FIFO_ENG_COPY2	4
#define NVRM_FIFO_ENG_VP	5
#define NVRM_FIFO_ENG_ME	6
#define NVRM_FIFO_ENG_PPP	7
#define NVRM_FIFO_ENG_BSP	8
#define NVRM_FIFO_ENG_MPEG	9
#define NVRM_FIFO_ENG_SOFTWARE	10
#define NVRM_FIFO_ENG_CRYPT	11
/* XXX 12? */
#define NVRM_FIFO_ENG_VENC	13
/* XXX 15? */

#endif
