# Makefile
TARGET	= user_test
CC	= gcc
NVCC	= nvcc -arch sm_20
LIBS	= -lenvyrt -ldrm
CFLAGS	= -I /usr/local/cuda/include
SRC	= $(wildcard ./*.cu)

all:
	$(CC) main.c -o $(TARGET) $(CFLAGS) $(LIBS)

clean:
	rm -f $(TARGET) ./*~
