/*
 * Copyright (C) Shinpei Kato
 * All Rights Reserved
 *
 * This is automatically generated by autogen.sh script.
 *
 */

#ifndef __GDEV_AUTOGEN_H__
#define __GDEV_AUTOGEN_H__

#define GDEV_DRIVER_${DRIVER_NAME}

#endif
