# The following must be provided:
# A path to CUDA top directory
CUDA_TOP_DIR := ..
# An executable name
EXECUTABLE  := bfs
# Cuda source files (compiled with cudacc)
CUFILES     := bfs_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES     := bfs.c

include ../util/nvidia.mk