# Makefile
TARGET	= user_test
CC	= gcc
NVCC	= nvcc -arch sm_20 -cubin
LIBS	= -lcuda
CFLAGS	= -I /usr/local/cuda/include

all:
	$(NVCC) -o matrixmul_gpu.cubin matrixmul_gpu.cu
	gcc -o $(TARGET) $(CFLAGS) $(LIBS) main.c matrixmul.c

clean:
	rm -f $(TARGET) *.cubin ./*~
