# The following must be provided:
# A path to CUDA top directory
CUDA_TOP_DIR := ..
# An executable name
EXECUTABLE  := nn
# Cuda source files (compiled with cudacc)
CUFILES     := nn_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES     := nn_cuda.c
CC	:= g++ 

include ../util/nvidia.mk

hurricane_gen : hurricane_gen.c
	$(LOCAL_CC) -o $@ $< -lm

#data :
#       mkdir data
#       ./gen_dataset.sh

